version: '3'
services: 
  pmcm-api:
    build:
      context: .
    env_file: ./.env
    command: bash -c "yarn migrate:docker && yarn dev"
    volumes: 
      - .:/app/
      - /app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on: 
      - pmcm-db
    environment: 
      MYSQL_HOST: pmcm-db

  pmcm-db:
    image: postgres:13
    env_file: ./.env
    environment: 
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    # volumes:
    #   - mysql:/var/lib/mysql
    #   - mysql_config:/etc/mysql

# volumes:
#   mysql:
#   mysql_config: