services:
  GroupRepository:
    class: ../Group/infrastructure/PostgresGroupRepository
  FileRepository:
    class: ../File/infrastructure/AwsRepository

  GroupCreate:
    class: ../Group/application/GroupCreate
    arguments: ['@GroupRepository', '@FileRepository']